language: php
php:
- '5.4'
- '5.5'
- '5.6'
- '7.0'
- hhvm
- nightly
script:
 - php -r 'echo "yahoo";'
 - hadolint
 - cat /etc/issue
 - apt install hadolint -y
 
notifications:
  slack:
    rooms:
      secure: A4GTO6dUZ2eAjlixEdViPx7ttuIIqRCvCGnVTOtquWayReFb9YCk+dkmnOKupmvug++9SL2rv3VK72XWQvXk6zDhxzxx4aLjh2QU6KmPA3Yf9IRNTmPXgoM1R//BdpFXYdmo612fwCnJ2vBhgm3V7LSHKbuN268PB5vFcHcdCCOMShskW5odHAzJIvJV63gvJi6i3LZg+0ypIZ9d77jQTcxk/da0THT+aOY+fld8KfFE43Rq/XDCi0IsAClqKAyhwEVj2G1tWqV0GyfGoJi8TXeQmiadpg2lq53Xw2kF4uewSD+BZ6eQ/m0xEe8noAWMPjJROahTkQ+wkuxEGD3+tquyxVUYtP0hpSX0hk+SzfTd80NOaOdrVL5Nsp5UJ3/AMCVQbShExzAUU+Fw4TxkXfSQRrlcGCwjgSjtykJhiOSdGu4s2oMRrXs0iEKzk+ZYsz8ZZOTFgkr7FNPO63ENwU35oSlcV78GK5HjQBFv6sM9TYBtf5riLyOHOj1U2aWrEGUAgybmNo8AMM89HU1uS0zM+Dmw0H0khF2ekx1Hq7F6qIFCvd74Sz+SQcCd2ptp75lwyMAAS/hoxy5ygxEa0acle2IifJmga9VLT1rZGhUrRNVuGAvxOuc3eL0/hsDBhdOlz8+LOFAtmkj95k3wjii86XYh7JnsPMJ/sX6xG9k=
